### ISSUE TITLE
异质图节点分类

### ISSUE THREAD

**Issue by yufeng1027** [ZhuYun97/RoSA#2]
麻烦请问Rosa在异质图的节点分类任务上的数据集也是由pyg提供的吗，请问可以提供异质图在节点分类任务上的代码吗，想向您学习一下

**Comment by ZhuYun97** [comment]
Yes, the heterophilous datasets also come from pyg library. Now the repo also supports these datasets. You can run ROSA on these datasets easily:
```cmd
python train.py --dataset Cornell --ad True
python train.py --dataset Wisconsin --ad True
python train.py --dataset Texas --ad True
```

**Comment by yufeng1027** [comment]
您好，请问可以提供异构图使用mlp进行编码的代码吗，我复现的代码没有达到您的性能，想学习一下自己哪里出了问题，如果能得到回复，万分感谢
